from sqlalchemy import Column, Integer, String, DateTime, Numeric, BigInteger
from Models.SQL_SERVER.Base import Base

class Ocorrencia(Base):
    __tablename__ = 'tb_ocorr'
    __table_args__ = {'schema': 'intec.dbo'}

    # Chave Primária (Baseado na coluna codigo ser NO Nullable e numérica)
    codigo = Column(Numeric, primary_key=True)

    # --- Colunas Mapeadas via CSV ---
    filialctc = Column(String(10), nullable=False)
    numnf = Column(String(12))
    cod_ocorr = Column(String(2), nullable=False)
    emissaoctc = Column(DateTime)
    remet_cgc = Column(String(14))
    descr_ocorr = Column(String(40))
    usu_ocorr = Column(String(20))
    usu_dataocorr = Column(DateTime)
    data = Column(DateTime)
    hora = Column(String(5))
    atend_sacweb = Column(Numeric)
    obs_ocorr = Column(String(305))
    obs_ocorrcli = Column(String(305))
    baixadopre = Column(String(1))
    dtbaixapre = Column(DateTime)
    hsbaixapre = Column(String(5))
    recebpre = Column(String(25))
    usu_bxpre = Column(String(10))
    usu_datapre = Column(DateTime)
    baixadofinal = Column(String(1))
    dtbaixa = Column(DateTime)
    hsbaixa = Column(String(5))
    receb = Column(String(25))
    usu_bx = Column(String(10))
    usu_databx = Column(DateTime)
    atualprazo = Column(String(1))
    prazoentr = Column(Numeric)
    diasuteis = Column(Numeric)
    abonodias = Column(Numeric)
    usu_abono = Column(String(10))
    data_abono = Column(DateTime)
    obs_abono = Column(String(40))
    email_enviadoCLI = Column(String(1))
    email_dataCLI = Column(DateTime)
    email_enviadoSAC = Column(String(1))
    email_dataSAC = Column(DateTime)
    email_enviadoINT = Column(String(1))
    email_dataINT = Column(DateTime)
    atual_sitla = Column(String(1))
    at_sitla_data = Column(DateTime)
    rel_arquivo = Column(String(1))
    rel_arq_data = Column(DateTime)
    rel_arq_num = Column(Numeric)
    at_ocorr_cif = Column(String(1))
    at_ocorr_cif_data = Column(DateTime)
    canhotonf = Column(String(1))
    at_edi = Column(String(1))
    at_edi_data = Column(DateTime)
    ProtocoloIB = Column(BigInteger) # Tipo 'bigint'
    Usu_Comp = Column(String(50))